/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WealthRouteImport } from './routes/wealth'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as HobbyRouteImport } from './routes/hobby'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'

const WealthRoute = WealthRouteImport.update({
  id: '/wealth',
  path: '/wealth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbyRoute = HobbyRouteImport.update({
  id: '/hobby',
  path: '/hobby',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/fitness': typeof FitnessRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/hobby': typeof HobbyRoute
  '/investing': typeof InvestingRoute
  '/journal': typeof JournalRoute
  '/notes': typeof NotesRoute
  '/nutrition': typeof NutritionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/wealth': typeof WealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/fitness': typeof FitnessRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/hobby': typeof HobbyRoute
  '/investing': typeof InvestingRoute
  '/journal': typeof JournalRoute
  '/notes': typeof NotesRoute
  '/nutrition': typeof NutritionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/wealth': typeof WealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/fitness': typeof FitnessRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/hobby': typeof HobbyRoute
  '/investing': typeof InvestingRoute
  '/journal': typeof JournalRoute
  '/notes': typeof NotesRoute
  '/nutrition': typeof NutritionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/wealth': typeof WealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/calendar'
    | '/fitness'
    | '/focus'
    | '/goals'
    | '/hobby'
    | '/investing'
    | '/journal'
    | '/notes'
    | '/nutrition'
    | '/reports'
    | '/settings'
    | '/wealth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business'
    | '/calendar'
    | '/fitness'
    | '/focus'
    | '/goals'
    | '/hobby'
    | '/investing'
    | '/journal'
    | '/notes'
    | '/nutrition'
    | '/reports'
    | '/settings'
    | '/wealth'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/calendar'
    | '/fitness'
    | '/focus'
    | '/goals'
    | '/hobby'
    | '/investing'
    | '/journal'
    | '/notes'
    | '/nutrition'
    | '/reports'
    | '/settings'
    | '/wealth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  CalendarRoute: typeof CalendarRoute
  FitnessRoute: typeof FitnessRoute
  FocusRoute: typeof FocusRoute
  GoalsRoute: typeof GoalsRoute
  HobbyRoute: typeof HobbyRoute
  InvestingRoute: typeof InvestingRoute
  JournalRoute: typeof JournalRoute
  NotesRoute: typeof NotesRoute
  NutritionRoute: typeof NutritionRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WealthRoute: typeof WealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wealth': {
      id: '/wealth'
      path: '/wealth'
      fullPath: '/wealth'
      preLoaderRoute: typeof WealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobby': {
      id: '/hobby'
      path: '/hobby'
      fullPath: '/hobby'
      preLoaderRoute: typeof HobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  CalendarRoute: CalendarRoute,
  FitnessRoute: FitnessRoute,
  FocusRoute: FocusRoute,
  GoalsRoute: GoalsRoute,
  HobbyRoute: HobbyRoute,
  InvestingRoute: InvestingRoute,
  JournalRoute: JournalRoute,
  NotesRoute: NotesRoute,
  NutritionRoute: NutritionRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WealthRoute: WealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
